project_id = "cpaqhwutaypayfaqthip"

[functions.tribopay-checkout]
verify_jwt = false

[functions.tribopay-webhook]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.send-daily-push]
verify_jwt = false
