project_id = "cpaqhwutaypayfaqthip"

[functions.tribopay-checkout]
verify_jwt = false

[functions.tribopay-webhook]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.send-daily-push]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.generate-vapid-keys]
verify_jwt = false
